version: '3'
services:

  redis:
    image: 'redis'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app"

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask

volumes:
  redis:
