# Use an official Python runtime as a parent image
FROM python:3.7.4

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# uwsgi listening
EXPOSE 5001

# Launch uwsgi
CMD [ "uwsgi", "--ini", "uwsgi.ini" ]
